services:
  db:
    image: postgres:16
    container_name: mmo_db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - mmo_db_data:/var/lib/postgresql/data

volumes:
  mmo_db_data: